services:

  connect-example-go:
#    image: ccr.ccs.tencentyun.com/kratos/gateway:v2.0.0
    image: harbor.apikv.com:5443/sumery/connect-example-backend:v1.2.19
#    platform: linux/amd64
    build:
      context: .
      target: final
    environment:
      HTTP_ADDR: 0.0.0.0:4000
      RUN_MODE: prod
    ports:
      - "0.0.0.0:4000:4000"
    container_name: connect-example-go
    restart: on-failure:3
#    environment:
#      - DISCOVERY_DSN=consul://apikv.com:8500
#      - DISCOVERY_CONFIG_PATH=ecommerce/gateway/config.yaml
#    volumes:
#      # 仅挂载本地配置文件（开发环境）
#      - ./dynamic-config:/app/dynamic-config
#    command: [ "/app/gateway" ]
#    networks:
#      - ecommerce
