apiVersion: v1
kind: Service
metadata:
  name: ecommerce-user-service
spec:
  externalTrafficPolicy: Local
  selector:
    app: ecommerce-user
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 30001
  type: LoadBalancer

